--- # 서버 세팅
server:
  port: 9978

--- # jsp 경로 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

--- # 개발 세팅
spring:
  devtools:
    # html, jsp 같은 컴파일이 필요없는 파일 라이브 리로드
    livereload:
      enabled: true
    # 자바코드 수정시 enabled
    restart:
      enabled: false

--- # 오라클 설정
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: oracle

--- # mybatis 설정
mybatis:
  # 설정
  config-location: classpath:mybatis/mybatis-config.xml
  # sql.xml 맵팽
  mapper-locations: classpath:sqlmapper/*.xml
  # configuration: 
  #   # VO에 맵핑시 DB 의 underscore 를 camelCase 로 변경
  #   map-underscore-to-camel-case: true